### ISSUE TITLE
Endpoint informação realtime de veículos

### ISSUE THREAD

**Issue by g-xavier** [carrismetropolitana/schedules-api#10]
Boas, eu estou a desenvolver uma aplicação mobile para uso pessoal em que me dava muito jeito filtrar a informação realtime por paragens, á semelhança do que a carris faz no site https://beta.carrismetropolitana.pt/stops/all. 

Ou seja para uma determinada paragem, sei que passa por exemplo a linha 1704 e pretendo saber qual o tempo de espera e o posicionamento geográfico do autocarro. Pelo que estive a ver no github da carris, a api beta apenas permite obter toda a informação de paragens com o endpoint /stops ou sabendo o id da paragem  com o endpoint /stops/:id/realtime (problema é não saber o id mas apenas a linha que passa lá Ex: 1704) e toda a informação do posicionamento geográfico dos veículos com o endpoint /vehicles, como eu pretendo saber essa informação apenas para uma determinada linha, iria obter demasiados dados com os endpoints que mencionei que não vou precisar.

Existe alguma maneira ou endpoint para obter a informação de tempo de espera e posicionamento geográfico do autocarro apenas para uma só linha sabendo o número desta Ex: 1704 ou um conjunto de limitado de linhas?

Muito obrigado desde já e parabéns pelo bom trabalho

**Comment by joao-vasconcelos** [comment]
Olá @g-xavier, obrigado pelo interesse no API.

Pelo que percebo a melhor forma de obter essa informação é através do endpoint `/vehicles`, que devolve todas as posições de todos os veículos em operação, assim como a viagem (`trip_id`) e o percurso (`pattern_id`) de cada um.

Adicionámos também os campos `line_id` e `route_id` a este objeto para ser mais simples esta associação.

Conhecendo o `pattern_id` é possível obter toda informação sobre o serviço, desde horários, shape, sequência de paragens e rotas e linhas correspondentes.

Muito obrigado! 🚌

**Comment by g-xavier** [comment]
Muito brigado pela resposta! Mas o meu grande problema é devido ao facto do endpoint /vehicles devolver todas as posições de todos os veículos em operação e não permitir filtrar por exemplo por line_id ou patter_id para obter essa informação apenas para uma determinada paragem. Numa aplicação móvel o volume de dados extraído, usando esse endpoint , iria ser muito superior ao utilizado e o facto de ter de chamar esse endpoint no mínimo de um em um minuto para obter informação atualizada iria consumir muitos dados móveis numa aplicação móvel.

Visto que tal endpoint não existe parece-me mesmo que terei de ir buscar a informação num todo, talvez no formato Protobuf para o tamanho do pedido ser menor.

Não sei se me estou a fazer entender, se tiver alguma dúvida no meu problema não hesite em dizer, agradeço mais uma vez a ajuda!

**Comment by joao-vasconcelos** [comment]
Percebo. Neste momento não está nos planos fazer este desenvolvimento, mas se algo mudar volto a dar notícias por aqui. O pedido das posições ser em bloco tem algumas vantagens, como a possibilidade de colocar em cache (incluindo cache no cliente) e reduzir a variabilidade de combinações possíveis. Um pedido a este endpoint tem mais ou menos 350 KB, portanto executando-o 3 vezes num minuto (atualizações de 20 em 20 segundos) gasta-se aproximadamente 1 MB.

Em protobuf é significativamente menos, portanto se este 1 MB/min não for aceitável então é mesmo recomendado o `/vehicles.pb`. Este endpoint no entanto não tem tantos atributos por veículo (pois segue o standard e é suposto ser utilizado em conjunto com o GTFS estático). A maior vantagem é que desenvolvendo uma vez é possível integrar mais operadores com o mesmo código.

Se estiver interessado em partilhar, temos muita curiosidade em conhecer os desenvolvimentos e a app!

**Comment by g-xavier** [comment]
Muito obrigado! Estou a entender, vou verificar se o pedido ao endpoint /vehicles.pb tem os atributos que necessito e já volto a dar notícias! Só não estou a ver qual a ligação entre guardar em cache do lado do cliente e reduzir a variabilidade de combinações possíveis... Consegues explicar melhor o que querias dizer com isso? Sou novo no mundo da programação e não estou mesmo a ver. Se a aplicação estiver digna terei todo o gosto em partilhar ahahah mas de momento ainda está em fase alpha

**Comment by ricardojorgerm** [comment]
(Nota, não sou parte da TML)

@g-xavier Vi que ficou a sua pergunta para responder e eu achei-a interessante portanto vou dar uma achega. Para entender melhor como se planeia uma implementação de API do lado de quem a desenvolve, sugiro a leitura de 

- https://www.amazon.com/dp/0596805829/ref=as_li_ss_til 
- https://www.amazon.com/RESTful-Web-Services-Cookbook-Scalability/dp/0596801688/ref=pd_bxgy_d_sccl_1/147-1704247-5342737

De forma sucinta, o servidor da TML tem de ser capaz de lidar com milhares de pedidos a cada minuto com a informação atualizada, sem falhar. Se existir um ponto único de informação para todos os autocarros, é simples de a fornecer a vários milhares de pedidos com a mesma informação, e quando existam modificações, é simples de manter atualizado para todos os pedidos subsequentes no mesmo local.

Ora, consideremos a sua proposta. Se for oferecida a possibilidade de "personalizar" cada pedido (filtrando, por exemplo, por linha), então há necessidade de gerar uma resposta **nova** a cada cliente adequadamente filtrada consoante esse mesmo pedido. Embora não seja algo muito custoso e seja muito fácil de programar, acontece que em situações de grande carga quando existem muitos pedidos, a diferença de estar a calcular listas filtradas à medida de cada pedido versus fornecer sempre o mesmo pedido torna-se bastante grande e importante. 

Essa diferença tende a ser maior quanto mais volume for esperado. E a verdade é que sendo um sistema de tempo real, é expectável que cada utilizador faça muitos pedidos, e muito frequentes, e que haja muitos utilizadores ao mesmo tempo, pelo que é importante não ter de calcular milhares de "vistas" sobre os mesmos dados (esses filtros afinal, não são mais do que uma "vista" sobre os dados totais, ou seja, em parlanço de base de dados, uma "view"). Isto permite fornecer sempre a informação mais atual de forma igual para todos os requerentes. É o caminho correto para ter algo que funciona de forma mais estável e que não depende da carga.

Acontece também que a solução que propõe pode incentivar padrões de desenho erróneos. Imagine novamente que se fornece esse API filtrado por linha, mas o consumidor não pretende só uma linha, quer obter várias linhas. Isso significa uma de duas coisas:
- ou esse API filtrado suporta fornecer várias linhas nos parâmetros de filtragem, em array, o que vai tornar os pedidos ainda mais personalizados para combinações únicas de linhas, ao ponto que provavelmente é necessário calcular de propósito sempre cada combinação de cada cliente, pelo que não é possível ter caching do lado do servidor já que não há utilidade em reutilizar o resultado dessa combinação que será inválido após segundos devido à natureza do tempo real;
- ou alternativamente, o cliente decide fazer vários pedidos, um por cada linha, para enumerar o resultado pretendido; isto significa que de repente cada cliente passou a fazer N vezes mais pedidos e a carga aumentou multiplicativamente no servidor. Embora esta seja claramente a solução pior, nada impede ao cliente de fazer o mais fácil (for loop) e implementar enumeração em pedidos individuais, mesmo quando exista possibilidade de filtrar linhas em simultâneo.

Assim sendo, a solução correta é a implementada - receber todos os resultados (que não são assim tantos, especialmente tendo em conta a compressão gzip se solicitada, já que o formato JSON não é o mais eficiente mas com compressão em `Accept-Encoding` é aceitável), e responsabilizar o cliente pela filtragem correta. Na medida em que essa filtragem tenha algum custo residual, esse será imputado ao cliente, que poderá filtrar da forma que bem entender os dados recebidos.

É claro que há outros sistemas em que não há essa escolha: qualquer sistema que tenha demasiados resultados tem de ter alguma filtragem, como por exemplo a questão das estimativas de tempo por paragem, já que existem 12 mil paragens. Mas mesmo esses sistemas tem alguns cuidados para tentarem reutilizar respostas, e na medida que não tenham, sugiro à TML que os implemente para por exemplo, evitar que uma página web de uma linha com 100 paragens emita 100 pedidos por cliente para estimativas.

**Comment by g-xavier** [comment]
@ricardojorgerm Boa tarde, muito obrigado pela resposta detalhada e muito esclarecedora, bem como a recomendação de livros! Se já os tivesse lido, provavelmente não teria feito a recomendação que fiz. Faz todo o sentido a solução adoptada e faz ainda mais sentido agora aprofundar os meus conhecimentos sobre o assunto, a sua resposta fez-me perceber que realmente não sei do que falo :) Obrigado mais uma vez!
