### ISSUE TITLE
realtime endpoint is returning HTTP code 500

### ISSUE THREAD

**Issue by snps-grafael** [carrismetropolitana/schedules-api#11]
The `stops` page is not working, it shows "Sem Serviço". The `realtime` endpoint returns the following:

```
{"statusCode":500,"error":"Internal Server Error","message":"Unexpected token 'u', \"upstream c\"... is not valid JSON"}
```

**Comment by joao-vasconcelos** [comment]
Hello @snps-grafael, there is a temporary instability with the realtime service. A notice has been put on the website. It should be resolved shortly. Thanks for the alert!
