### ISSUE TITLE
timeframe for the 3 missing municipalities 

### ISSUE THREAD

**Issue by alexdeloy** [carrismetropolitana/schedules-api#15]
First of all: Thank you for your amazing work here @joao-vasconcelos 
Is there a timeframe for the missing municipalities to be added to the API? I found it quite odd to see Marvila and Beato among them, given that a big depot is in Chelas and the new tech hub is growing in Beato.

**Comment by joao-vasconcelos** [comment]
Hey @alexdeloy, thanks a lot!
This is the API for [Carris Metropolitana](https://carrismetropolitana.pt), which is the bus operator for 15 of the 18 municipalities of the Lisbon Metropolitan Area.
The neighborhoods you mention are all part of the Lisbon municipality, which has its own local operator ([Carris municipal](https://carris.pt)). Even though we have a _similar_ name we are actually different companies. [More details here.](https://github.com/MobilityData/mobility-database-catalogs/pull/281#issuecomment-1637199406)

You can find the static and real-time GTFS for Carris municipal here: https://gateway.carris.pt/apiui/#!/

Thanks again for your interest in the API 🚌

**Comment by alexdeloy** [comment]
Thank you so much for that clarification, that is very confusing indeed but it makes sense now!
