### ISSUE TITLE
Real Time - apple maps

### ISSUE THREAD

**Issue by nevespt** [carrismetropolitana/schedules-api#16]
Olá,
Da mesma forma que foi possível fazer com o google maps, seria possível fazer a implementação no apple maps?

**Comment by joao-vasconcelos** [comment]
Boa tarde @nevespt, o feed GTFS-RT foi disponibilizado em simultâneo e gratuitamente para as principais apps (Citymapper, Moovit, Google e Apple), e é um [sistema aberto a qualquer pessoa](https://api.carrismetropolitana.pt). Após vários contactos com a Apple nunca obtivemos resposta. Aguardamos feedback desde Novembro de 2023.
