### ISSUE TITLE
Missing Unit Tests 

### ISSUE THREAD

**Issue by GloverChris** [carrismetropolitana/schedules-api#22]
Both the website pieces and the api are missing unit tests to ensure program is functioning appropriately. Needs test to make sure API backend and front end stay aligned and ensures data is returned as expected from various sources

**Comment by joao-vasconcelos** [comment]
Hey @GloverChris, thanks for your comment. We're aware of the need of tests and would like to have them at some point in the future, and we're not able to work only on what we'd like :P
If you're interested, a PR would be very much appreciated!

**Comment by GloverChris** [comment]
Sure, Ill set some time aside and help you guys out.
