### ISSUE TITLE
API Bad gateway response

### ISSUE THREAD

**Issue by dinisduarte220** [carrismetropolitana/schedules-api#28]
Boas, tenho um projeto so para mim que usa a API.
99% das linhas funcionam bem quando eu faço um request das routes a API, notei que por exemplo na linha 1002 ele demora muito tempo a responder e acaba por responder com "Bad Gateway" erro 502
Usie o link do request no browser e reparei que ele de facto demora imenso tempo, mas so nessa linha (ainda nao vi nenhuma com o mesmo problema)

sabem o que possa ser?

**Comment by joao-vasconcelos** [comment]
Olá @dinisduarte220! Aqui tudo parece funcionar normalmente. Consegues dar os URLs exatos dos pedidos? É no /lines /routes ou /patterns ?

**Comment by dinisduarte220** [comment]
O problema era no URL https://api.carrismetropolitana.pt/patterns/1002_0_3. Mas parece que ja nao ocorre o mesmo erro, obrigado na mesma!
