### ISSUE TITLE
RealTime

### ISSUE THREAD

**Issue by dinisduarte220** [carrismetropolitana/schedules-api#31]
Boas denovo :)
Estou a criar um projeto com a vossa API, que digo que esta incrivel e muito acessivel. Mas verifiquei agora que no real time "stops/:id/realtime", algumas passagens que ja ocorreram tem o observed_time como null. Um exemplo que encontrei (de muitos) foi este:

{
"estimated_arrival": "06:51:46",
"estimated_arrival_unix": 1729489906,
"headsign": "Estação Oriente",
"line_id": "2728",
"observed_arrival": null,
"observed_arrival_unix": null,
"pattern_id": "2728_0_1",
"route_id": "2728_0",
"scheduled_arrival": "06:45:03",
"scheduled_arrival_unix": 1729489503,
"stop_sequence": 26,
"trip_id": "2728_0_1|1|1|0615_DEPGY",
"vehicle_id": "42|2411"
}

estava a organizar as passagens e para marcar as concluidas usava o observed time !== null, mas apareciam demais e vi que algo estava errado

Sao 22:40 e ate pensei que fosse o autocarro que nao tivesse passado, mas penso que a partir do momento que tem estimated time, ele esta em movimento.

Obrigado por tudo desde ja!
Cumprimentos

**Comment by joao-vasconcelos** [comment]
Olá @dinisduarte220, o estimador de horários poderá não ter detetado corretamente que o veículo serviu essa paragem. Pode ser que não se tenha recebido nenhum evento dentro da geofence dessa paragem, ou que esse evento tenha sido recebido fora de ordem. Neste momento não há outra forma de verificar se o veículo serviu ou não uma paragem, a não ser "manualmente" através da análise das sucessivas posições dos veículos. É possível que no futuro fique disponível uma implementação ou o resultado da implementação desta funcionalidade.

**Comment by Movs22** [comment]
Eu pessoalmente utilizo o endpoint dos veículos (https://api.carrismetropolitana.pt/vehicles) para verificar se o veículo ainda está a circular (ao verificar se existe um veículo a circular com o mesmo TRIP_ID que o que aparece no /realtime).
Adicionalmente, eu também filtro os resultados do /realtime para apenas incluirem as partidas que ocorreram à, pelo menos, 30 minutos (embora este seja apenas um valor arbritário dado que, na Zona 1, os veículos nunca chegaram a estar com 30+ minutos de atraso). Embora, como é claro, isto pode não funcionar para o seu caso em específico.
(P.S: Boa sorte com o seu projeto)

**Comment by dinisduarte220** [comment]
Entendo que nem tudo é perfeito ahah. Mas sim, ja dei a volta a situação em termos de verificar a passagem numa certa paragem
Muito Obrigado por ambas respostas!
@Movs22 @joao-vasconcelos
