### ISSUE TITLE
Missing real time data for some buses

### ISSUE THREAD

**Issue by andirsun** [carrismetropolitana/schedules-api#6]
Hey, I am testing the new website that shows the real time data of the buses.
I am wondering why are some buses that are not showing up for example
#753
![image](https://github.com/carrismetropolitana/api/assets/22928302/4f1855ab-b273-4877-b457-ab775eb26e5e)
![image](https://github.com/carrismetropolitana/api/assets/22928302/8647aea2-5df0-4552-857a-6c88abb906db)

**Comment by joao-vasconcelos** [comment]
Hello @andirsun! Thanks for your interest in the API! The bus in the image is from the municipal operator for Lisbon, "Carris municipal" (carris.pt).

We are [Carris Metropolitana](https://www.carrismetropolitana.pt), which operates in 15 of the 18 municipalities in the greater Lisbon area. I refere you to this comment in the Mobility Database repo where it is better explained: https://github.com/MobilityData/mobility-database-catalogs/pull/281#issuecomment-1637199406

Carris municipal also has an API available (in GTFS-RT format): https://gateway.carris.pt/apiui/#!/apis

I wish you the best of luck in your developments!
