### ISSUE TITLE
Buses are correctly tracked, but no expected arrival time is available

### ISSUE THREAD

**Issue by goncrafa** [carrismetropolitana/schedules-api#7]
Greetings,
I have noticed this issue mostly on the 1601 line, specifically in the 121171 stop (Estrada de Oeiras, Inst. Condessa de Cuba).
When a schedule is selected in the UI, it uses the bus ID included in the `stops/121171/realtime` endpoint, and the bus tracking data is fetched (from the `vehicles` endpoint).
However, the expected arrival isn't being populated any more (as seen in the attached screenshot).

![Bus is shown approaching stop, arrival is 11 minutes after schedule, it is not shown as arriving or on the way, no expected time is shown](https://github.com/carrismetropolitana/api/assets/117039833/daa7635d-513f-4497-9b3b-b632414e03ce)

(Bus is shown approaching stop, arrival is 11 minutes after schedule, it is not shown as arriving or on the way, no expected time is shown) 

(Minor note that this service greatly improves my quality-of-life, so I'm very thankful and enthusiastic for this project).

**Comment by joao-vasconcelos** [comment]
Hello @goncrafa! We're aware of the issue with the lack of estimates on several trips. I can't tell you exactly when this will be resolved but we're actively working on it. Expect improvements in the coming weeks. Thanks for the report and your interest in the API : )
