### ISSUE TITLE
Horários na API

### ISSUE THREAD

**Issue by ruinunes57** [carrismetropolitana/schedules-api#8]
Olá
Estou a tentar obter os horários das linhas através da API mas não existe nenhum endpoint schedules, como é que eu consigo aceder aos horários das linhas através da API?
Cumprimentos.

**Comment by joao-vasconcelos** [comment]
Olá @ruinunes57, os horários estão disponíveis através do endpoint `/patterns/:pattern_id`. Neste objeto existe uma array de `trips` que contém informações sobre todas as viagens desse percurso. Planeamos lançar um endpoint dedicado para construir as tabelas de horários mais facilmente, mas para já é necessário manipular essa array de trips em função da data em que cada trip é válida e a paragem desejada. Quando este novo endpoint for lançado atualizaremos por aqui. Obrigado!
