### ISSUE TITLE
Horas de passagem

### ISSUE THREAD

**Issue by dinisduarte220** [carrismetropolitana/schedules-api#9]
As horas de passagem estam a ser mostradas de acordo com a API
Mas as horas são diferentes no site da empresa
Será a API que está errada?

**Comment by joao-vasconcelos** [comment]
Olá @dinisduarte220, é possível detalhar um pouco mais o Issue? Confesso que não percebi. Obrigado!

**Comment by dinisduarte220** [comment]
Olá, boa noite. Sim claro! Desculpe
Estou a desenvolver um programa para uso proprio e ao recolher os horários pelo trip.id do endPoint "patterns", os mesmos fornecidos pela API são diferentes dos apresentados no site da Carris Metropolitana
Com a mesma data, hora, sentido e rota

Pensei que fosse erro meu ao recolher os horarios da API e que estivesse a recolher do id errado, mas depois reparei que esta certo e igual ao id usado no site oficial.

Queria saber se é um problema da API ou se os horários do site são retirados de um sitio diferente

**Comment by joao-vasconcelos** [comment]
O site consome o mesmo API público, no entanto o site [www.carrismetropolitana.pt/horarios](https://www.carrismetropolitana.pt/horarios) consome a [versão anterior do API](https://github.com/carrismetropolitana/api/tree/production) e o [site beta](https://beta.carrismetropolitana.pt/lines) consome a [versão beta do API](https://github.com/carrismetropolitana/api).

Houve algumas alterações na forma como são "calculados" os horários por pattern.

É possível dar um exemplo de uma linha?

**Comment by dinisduarte220** [comment]
Estive a conferir o site beta e acho que é esse mesmo o problema ahahah
Por exemplo, linha 4600 sentido Barreiro (Terminal), na paragem Lançada (EN 11 72), no dia 09/01/2024, 06:00h
A API apreseta 06:42 a hora de passagem e no site oficial apresenta 06:47
E na ultima paragem da linha com os mesmos detalhes apresente 07:28, na API 07:20

**Comment by joao-vasconcelos** [comment]
Obrigado! Vamos investigar

**Comment by joao-vasconcelos** [comment]
@dinisduarte220, à partida o API beta está correto. A informação do API e site BETA bate certo com a informação raw do GTFS. Vamos verificar mais circulações para perceber o porquê da diferença entre planos e corrigir. De qualquer forma, o API anterior está para ser descontinuado em breve. Vamos acelerar o processo de transição para o novo. Dou novidades em breve!

![Screenshot 2024-01-09 at 12 09 40](https://github.com/carrismetropolitana/api/assets/10943992/a5c19757-8301-44dc-bb4f-a037404c6f61)

**Comment by dinisduarte220** [comment]
Muito obrigado! 
É só porque como passageiro, fiava-me nos horários do site "antigo" e acabava sempre por me enganar 
Fico à espera de novidades :)

**Comment by joao-vasconcelos** [comment]
Claro! É também possível que seja um erro do plano, e nesse caso o erro existe apenas desde 1 Jan 2024. Os horários em formato standard e raw estão disponíveis em todas as apps (Google, Citymapper, Moovit, Apple, etc.) e nunca foi detetada nenhuma divergência com o site. Agora com tempo real é a forma mais precisa de viajar, pois sabe-se exatamente onde anda o autocarro ;)

**Comment by dinisduarte220** [comment]
Tempo Real foi a melhor novidade que lançaram! Já não viajo de outra forma
Sim, ja entendi que a informações estava correta, só que uma era informação antiga e a outra não

Obrigado pelas respostas rápidas, ajudou bastante!
